Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job               count
--------------  -------
all                   1
inst_cap_table       72
total                73

Select jobs to execute...

[Wed Jun 12 20:19:53 2024]
rule inst_cap_table:
    input: resources/DE_20_1.0_pv_0_180_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0_180_inv.csv
    jobid: 4
    reason: Missing output files: results/data/DE/pv/DE_20_1.0_pv_0_180_inv.csv
    wildcards: country=DE, contingency=pv, buses=20, transmission_limit=1.0, reductionto=0, duration=180, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp


[Wed Jun 12 20:19:53 2024]
rule inst_cap_table:
    input: resources/DE_20_1.0_pv_0.5_270_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0.5_270_inv.csv
    jobid: 18
    reason: Missing output files: results/data/DE/pv/DE_20_1.0_pv_0.5_270_inv.csv
    wildcards: country=DE, contingency=pv, buses=20, transmission_limit=1.0, reductionto=0.5, duration=270, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp


[Wed Jun 12 20:19:53 2024]
rule inst_cap_table:
    input: resources/DE_20_1.0_pv_0.25_90_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0.25_90_inv.csv
    jobid: 8
    reason: Missing output files: results/data/DE/pv/DE_20_1.0_pv_0.25_90_inv.csv
    wildcards: country=DE, contingency=pv, buses=20, transmission_limit=1.0, reductionto=0.25, duration=90, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp


[Wed Jun 12 20:19:53 2024]
rule inst_cap_table:
    input: resources/DE_20_1.0_pv_0_90_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0_90_inv.csv
    jobid: 1
    reason: Missing output files: results/data/DE/pv/DE_20_1.0_pv_0_90_inv.csv
    wildcards: country=DE, contingency=pv, buses=20, transmission_limit=1.0, reductionto=0, duration=90, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Wed Jun 12 20:20:02 2024]
Error in rule inst_cap_table:
    jobid: 4
    input: resources/DE_20_1.0_pv_0_180_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0_180_inv.csv

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 185:
Command 'python scripts/inst_cap.py resources/DE_20_1.0_pv_0_180_inv.nc results/data/DE/pv/DE_20_1.0_pv_0_180_inv.csv' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 185, in __rule_inst_cap_table
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Wed Jun 12 20:20:02 2024]
Error in rule inst_cap_table:
    jobid: 1
    input: resources/DE_20_1.0_pv_0_90_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0_90_inv.csv

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 185:
Command 'python scripts/inst_cap.py resources/DE_20_1.0_pv_0_90_inv.nc results/data/DE/pv/DE_20_1.0_pv_0_90_inv.csv' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 185, in __rule_inst_cap_table
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Wed Jun 12 20:20:02 2024]
Error in rule inst_cap_table:
    jobid: 8
    input: resources/DE_20_1.0_pv_0.25_90_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0.25_90_inv.csv

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 185:
Command 'python scripts/inst_cap.py resources/DE_20_1.0_pv_0.25_90_inv.nc results/data/DE/pv/DE_20_1.0_pv_0.25_90_inv.csv' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 185, in __rule_inst_cap_table
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Wed Jun 12 20:20:02 2024]
Error in rule inst_cap_table:
    jobid: 18
    input: resources/DE_20_1.0_pv_0.5_270_inv.nc
    output: results/data/DE/pv/DE_20_1.0_pv_0.5_270_inv.csv

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 185:
Command 'python scripts/inst_cap.py resources/DE_20_1.0_pv_0.5_270_inv.nc results/data/DE/pv/DE_20_1.0_pv_0.5_270_inv.csv' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 185, in __rule_inst_cap_table
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-06-12T201952.586610.snakemake.log
