Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
dynamic_solve       36
total               37

Select jobs to execute...

[Sun Jun 16 22:02:28 2024]
rule dynamic_solve:
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.5_90_noinv.nc, results/DE_20_1.5_pv_0.5_90_noinvroll.nc
    jobid: 36
    reason: Missing output files: results/DE_20_1.5_pv_0.5_90_noinvroll.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5, contingency=pv, reductionto=0.5, duration=90, model=noinv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sun Jun 16 22:02:28 2024]
rule dynamic_solve:
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.25_270_noinv.nc, results/DE_20_1.5_pv_0.25_270_noinvroll.nc
    jobid: 35
    reason: Missing output files: results/DE_20_1.5_pv_0.25_270_noinvroll.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5, contingency=pv, reductionto=0.25, duration=270, model=noinv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp


[Sun Jun 16 22:02:28 2024]
rule dynamic_solve:
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.5_90_inv.nc, results/DE_20_1.5_pv_0.5_90_invroll.nc
    jobid: 27
    reason: Missing output files: results/DE_20_1.5_pv_0.5_90_invroll.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5, contingency=pv, reductionto=0.5, duration=90, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sun Jun 16 22:02:28 2024]
rule dynamic_solve:
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0_180_inv.nc, results/DE_20_1.5_pv_0_180_invroll.nc
    jobid: 22
    reason: Missing output files: results/DE_20_1.5_pv_0_180_invroll.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5, contingency=pv, reductionto=0, duration=180, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sun Jun 16 22:02:42 2024]
Error in rule dynamic_solve:
    jobid: 36
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.5_90_noinv.nc, results/DE_20_1.5_pv_0.5_90_noinvroll.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 170:
Command 'python scripts/solve_pv.py resources/DE_20_1.5_base_solved.nc resources/DE_20_1.5_pv_0.5_90_noinv.nc results/DE_20_1.5_pv_0.5_90_noinvroll.nc pv 0.5 90 noinv 52 DE EQ0.95c 1.5 20' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 170, in __rule_dynamic_solve
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Sun Jun 16 22:02:42 2024]
Error in rule dynamic_solve:
    jobid: 35
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.25_270_noinv.nc, results/DE_20_1.5_pv_0.25_270_noinvroll.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 170:
Command 'python scripts/solve_pv.py resources/DE_20_1.5_base_solved.nc resources/DE_20_1.5_pv_0.25_270_noinv.nc results/DE_20_1.5_pv_0.25_270_noinvroll.nc pv 0.25 270 noinv 52 DE EQ0.95c 1.5 20' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 170, in __rule_dynamic_solve
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Sun Jun 16 22:02:52 2024]
Error in rule dynamic_solve:
    jobid: 22
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0_180_inv.nc, results/DE_20_1.5_pv_0_180_invroll.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 170:
Command 'python scripts/solve_pv.py resources/DE_20_1.5_base_solved.nc resources/DE_20_1.5_pv_0_180_inv.nc results/DE_20_1.5_pv_0_180_invroll.nc pv 0 180 inv 52 DE EQ0.95c 1.5 20' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 170, in __rule_dynamic_solve
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Sun Jun 16 22:02:53 2024]
Error in rule dynamic_solve:
    jobid: 27
    input: resources/DE_20_1.5_base_solved.nc
    output: resources/DE_20_1.5_pv_0.5_90_inv.nc, results/DE_20_1.5_pv_0.5_90_invroll.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 170:
Command 'python scripts/solve_pv.py resources/DE_20_1.5_base_solved.nc resources/DE_20_1.5_pv_0.5_90_inv.nc results/DE_20_1.5_pv_0.5_90_invroll.nc pv 0.5 90 inv 52 DE EQ0.95c 1.5 20' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 170, in __rule_dynamic_solve
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-06-16T220227.859614.snakemake.log
